apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - the-project-rollout.yaml
  - the-project-service.yaml
  - the-project-configmap.yaml
  - todo-backend-deployment.yaml
  - todo-backend-service.yaml
  - todo-backend-configmap.yaml
  - postgres-statefulset.yaml
  - migration-job.yaml
  - migration-configmap.yaml
  - broadcaster-deployment.yaml
  - sealed-secret.yaml
  - analysis-template.yaml
  - backendconfig.yaml
  - ingress.yaml

images:
  - name: PROJECT/IMAGE
    newName: gcr.io/useful-device-482607-p0/the-project
  - name: todo-backend:prod
    newName: gcr.io/useful-device-482607-p0/todo-backend
  - name: broadcaster:prod
    newName: gcr.io/useful-device-482607-p0/broadcaster
