apiVersion: v1
kind: ConfigMap
metadata:
  name: todo-backend-config
data:
  PORT: "3000"
  POSTGRES_HOST: "todo-postgres-stset-0.todo-postgres-svc"
  POSTGRES_PORT: "5432"
  POSTGRES_DB: "todos"
  POSTGRES_USER: "postgres"
  POSTGRES_PASSWORD: "postgres"
  NATS_URL: "nats://my-nats.default.svc.cluster.local:4222"
