apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: project
  name: the-project-ingress
spec:
  rules:
    - http:
        paths:
          - path: /the-project
            pathType: Prefix
            backend:
              service:
                name: the-project-svc
                port:
                  number: 3000
          - path: /todos
            pathType: Prefix
            backend:
              service:
                name: todo-backend-svc
                port:
                  number: 3000
