apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - configmap.yaml
  - rollout.yaml
  - analysis-template.yaml
  - service.yaml
  - backendconfig.yaml
  - ingress.yaml
images:
  - name: PROJECT/IMAGE
    newName: gcr.io/useful-device-482607-p0/the-project
