apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- configmap.yaml
- rollout.yaml
- analysis-template.yaml
- service.yaml
- backendconfig.yaml
- ingress.yaml
images:
- name: PROJECT/IMAGE
  newName: europe-north1-docker.pkg.dev/useful-device-482607-p0/dwk-repository/the-project
  newTag: main-9b571149151c6172ed9845395317cb08ef93a0d4
