apiVersion: v1
kind: Service
metadata:
  namespace: project
  name: the-project-svc
  annotations:
    cloud.google.com/backend-config: '{"default": "the-project-backendconfig"}'
spec:
  type: ClusterIP
  selector:
    app: the-project
  ports:
    - name: http
      protocol: TCP
      port: 3000
      targetPort: 3000
