apiVersion: v1
kind: Service
metadata:
  name: the-project-svc
spec:
  type: ClusterIP
  selector:
    app: the-project
  ports:
    - name: http
      protocol: TCP
      port: 3000
      targetPort: 3000
