apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: dummysites.stable.dwk
spec:
  group: stable.dwk
  names:
    kind: DummySite
    plural: dummysites
    singular: dummysite
    shortNames:
      - ds
  scope: Namespaced
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                website_url:
                  type: string
              required:
                - website_url
      additionalPrinterColumns:
        - name: Website URL
          type: string
          jsonPath: .spec.website_url
        - name: Age
          type: date
          jsonPath: .metadata.creationTimestamp
