apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - configmap.yaml
  - postgres-statefulset.yaml
  - migration-configmap.yaml
  - migration-job.yaml
  - deployment.yaml
  - service.yaml
  - backup-cronjob.yaml
