apiVersion: v1
kind: ConfigMap
metadata:
  namespace: exercises
  name: ping-pong-config
data:
  PORT: "3000"
  POSTGRES_HOST: "postgres-stset-0.postgres-svc"
  POSTGRES_PORT: "5432"
  POSTGRES_DB: "pingpong"
  POSTGRES_USER: "postgres"
  POSTGRES_PASSWORD: "postgres"
