apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: exercises
  name: log-output-ingress
spec:
  rules:
    - http:
        paths:
          - path: /log-output
            pathType: Prefix
            backend:
              service:
                name: log-output-svc
                port:
                  number: 3000
          - path: /pingpong
            pathType: Prefix
            backend:
              service:
                name: ping-pong-svc
                port:
                  number: 3000
