apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: production

resources:
  - ../../base
  - backup-cronjob.yaml

images:
  - name: PROJECT/IMAGE
    newName: europe-north1-docker.pkg.dev/useful-device-482607-p0/dwk-repository/the-project
  - name: todo-backend:prod
    newName: europe-north1-docker.pkg.dev/useful-device-482607-p0/dwk-repository/todo-backend
  - name: broadcaster:prod
    newName: europe-north1-docker.pkg.dev/useful-device-482607-p0/dwk-repository/broadcaster
