apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: greeter
  namespace: default
spec:
  parentRefs:
  - group: ""
    kind: Service
    name: greeter-svc
    port: 80
  rules:
  - backendRefs:
    - group: ""
      kind: Service
      name: greeter-svc-v1
      port: 80
      weight: 75
    - group: ""
      kind: Service
      name: greeter-svc-v2
      port: 80
      weight: 25
    matches:
    - path:
        type: PathPrefix
        value: /