name: Release the-project

on:
  push:
    branches:
      - '**'
    paths:
      - 'the_project/**'
      - '.github/workflows/the-project.yaml'

permissions:
  contents: write

env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  GKE_CLUSTER: dwk-cluster
  GKE_ZONE: europe-north1-b
  REGISTRY: europe-north1-docker.pkg.dev
  REPOSITORY: dwk-repository
  IMAGE: the-project
  SERVICE: the-project
  BRANCH: ${{ github.ref_name }}

jobs:
  build-publish-deploy:
    name: Build, Publish and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GKE_SA_KEY }}'

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Use gcloud CLI
        run: gcloud info

      - name: Configure Docker to use gcloud
        run: gcloud --quiet auth configure-docker ${{ env.REGISTRY }}

      - name: Form the image name
        run: echo "IMAGE_TAG=$REGISTRY/$PROJECT_ID/$REPOSITORY/$IMAGE:$BRANCH-$GITHUB_SHA" >> $GITHUB_ENV

      - name: Build
        working-directory: ./the_project
        run: docker build --platform linux/amd64 --tag $IMAGE_TAG .

      - name: Publish
        run: docker push $IMAGE_TAG

      - name: Set up Kustomize
        uses: imranismail/setup-kustomize@v2.1.0

      - name: Update image tag
        working-directory: ./the_project/manifests
        run: kustomize edit set image PROJECT/IMAGE=$IMAGE_TAG

      - name: Commit kustomization.yaml to GitHub
        uses: EndBug/add-and-commit@v9
        with:
          add: 'the_project/manifests/kustomization.yaml'
          message: New the-project version ${{ github.sha }}
